name: e_commerce_app_with_provider
description: "ShopWave - Modern E-Commerce App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5+1
  http: ^1.2.1
  path_provider: ^2.1.2
  connectivity_plus: ^7.1.1
  cached_network_image: ^3.4.1
  sqflite_common_ffi: ^2.4.0+3
  shared_preferences: ^2.2.2
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1

  sqflite: any
  path: any
  # flutter_localizations:
    # sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#030A17"
  color_dark: "#000000"
  image: "assets/icon/splash_icon.png"
  android_12:
    color: "#030A17"
    color_dark: "#000000"
    image: "assets/icon/splash_icon.png"

flutter:
  uses-material-design: true